### ISSUE TITLE
Ошибки при попытке получить инстанс Group

### ISSUE THREAD

**Issue by mcfoton** [ramusus/django-vkontakte-groups#2]
> > > Group.remote.fetch(ids=[16297716])

/Users/mcfoton/Documents/dev/learning/envs/gravitytool/lib/python2.7/site-packages/django/db/models/fields/**init**.py:827: RuntimeWarning: DateTimeField received a naive datetime (2015-01-20 23:46:52.156047) while time zone support is active.
  RuntimeWarning)

/Users/mcfoton/Documents/dev/learning/envs/gravitytool/lib/python2.7/site-packages/django/db/models/fields/**init**.py:827: RuntimeWarning: DateTimeField received a naive datetime (2015-01-20 23:46:52.155827) while time zone support is active.
  RuntimeWarning)

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/mcfoton/Documents/dev/learning/envs/gravitytool/src/django-vkontakte-groups/vkontakte_groups/models.py", line 57, in fetch
    return super(GroupRemoteManager, self).fetch(_args, *_kwargs)
  File "/Users/mcfoton/Documents/dev/learning/envs/gravitytool/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(_args, *_kwargs)
  File "/Users/mcfoton/Documents/dev/learning/envs/gravitytool/src/django-vkontakte-api/vkontakte_api/models.py", line 138, in fetch
    return self.model.objects.filter(pk__in=set([self.get_or_create_from_instance(instance).pk for instance in result]))
  File "/Users/mcfoton/Documents/dev/learning/envs/gravitytool/src/django-vkontakte-api/vkontakte_api/models.py", line 110, in get_or_create_from_instance
    vkontakte_api_post_fetch.send(sender=instance.**class**, instance=instance, created=(not old_instance))
UnboundLocalError: local variable 'old_instance' referenced before assignment

**Comment by ramusus** [comment]
сделай 

```
pip install -e git+git@github.com:ramusus/django-vkontakte-api.git#egg=django_vkontakte_api
```

и попробуй заново через шелл, у тебя старая версия приложения
